### PR TITLE
Bug fix redundent input for archive and load

### LINKED ISSUE #107: Fix the bug of allowing non-empty preamble in archive and load command
The commands allows input like archie fhuiahf pa/mybook.json.
This should not be allowed

### PR DESCRIPTION
**Pull request by Jianwen0451**
close #107

### CODE REVIEW

File: src/test/java/seedu/address/logic/parser/ArchiveCommandParserTest.java [hunk 1]
```diff
@@ -13,9 +13,10 @@
 import seedu.address.logic.commands.ArchiveCommand;
 
 public class ArchiveCommandParserTest {
-    private static final String INPUT_MISSING_PREFIX = "archive mybook.json";
-    private static final String INPUT_MULTIPLE_PATH = "archive pa/mybook.json pa/mybook2.json";
-    private static final String VALID_INPUT = "archive pa/TestValidInput.json";
+    private static final String INPUT_MISSING_PREFIX = " mybook.json";
+    private static final String INPUT_MULTIPLE_PATH = " pa/mybook.json pa/mybook2.json";
+    private static final String INPUT_NONEMPTY_PREAMBLE = " 1123454 pa/mybook.json";
+    private static final String VALID_INPUT = " pa/TestValidInput.json";
```
Comment (RadieonAjax) [inline src/test/java/seedu/address/logic/parser/ArchiveCommandParserTest.java:19]: Great improvement on cleaning up the string constants by removing the `archive` prefix! It makes the input paths much cleaner and easier to follow — nice work!

**Review by RadieonAjax — APPROVED** [review]
LGTM! This PR is concise and effectively enhances code clarity by refining constants and updating regular expressions for better input validation. The adjustments make the code more readable and maintainable. Great job!
